Repository monitoror/monitoror, pull requests merged in 2020-05, with the labels that each got.

#318 Feat improve config loading
  .env.example
  api/config/delivery/http/handlers.go
  api/config/delivery/http/handlers_test.go
  api/config/mocks/Usecase.go
  api/config/models/config.go
  api/config/models/configmetadata.go
  api/config/models/params.go
  api/config/models/params_test.go
  api/config/repository/file.go
  api/config/repository/file_test.go
  api/config/usecase.go
  api/config/usecase/getconfig.go
  api/config/usecase/getconfig_test.go
  api/config/usecase/hydrate.go
  api/config/usecase/hydrate_test.go
  api/config/usecase/usecase.go
  api/config/usecase/usecase_test.go
  api/config/usecase/verify.go
  api/config/usecase/verify_test.go
  cli/cli.go
  cli/cli_test.go
  config-example.json
  config/config.go
  config/config_test.go
  docs/documentation/index.html
  go.mod
  go.sum
  internal/pkg/env/env.go
  internal/pkg/env/env_test.go
  internal/pkg/monitorable/config/config.go
  internal/pkg/monitorable/config/config_test.go
  internal/pkg/monitorable/config/env.go
  internal/pkg/monitorable/config/env_test.go
  internal/pkg/monitorable/monitorable.go
  internal/pkg/monitorable/monitorable_faker.go
  internal/pkg/monitorable/monitorable_test.go
  internal/pkg/monitorable/test/monitorable.go
  internal/pkg/validator/validate/validate.go
  models/variant.go
  monitorables/monitorable_test.go
  monitorables/ping/ping_test.go
  service/api.go
  service/router/router_test.go
  service/server.go
  service/server_test.go
  service/store/store.go
  service/ui_test.go
  ui/src/components/Errors.vue
  ui/src/enums/configErrorId.ts
  ui/src/helpers/hasConfigVerifyErrors.ts
  ui/src/store.ts
Labels: core, documentation, feature, semver:major, ui

#312 Refactor GitHub pullrequests
  docs/documentation/index.html
  faker-configs/faker-build-config.json
  models/tilebuild.go
  monitorables/github/api/delivery/http/handlers.go
  monitorables/github/api/delivery/http/handlers_test.go
  monitorables/github/api/mocks/Repository.go
  monitorables/github/api/mocks/Usecase.go
  monitorables/github/api/models/checksparams_test.go
  monitorables/github/api/models/pullrequest.go
  monitorables/github/api/models/pullrequestparams.go
  monitorables/github/api/models/pullrequestparams_faker.go
  monitorables/github/api/models/pullrequestparams_test.go
  monitorables/github/api/repository.go
  monitorables/github/api/repository/api.go
  monitorables/github/api/repository/api_test.go
  monitorables/github/api/usecase.go
  monitorables/github/api/usecase/github.go
  monitorables/github/api/usecase/github_faker.go
  monitorables/github/api/usecase/github_test.go
  monitorables/github/github.go
  monitorables/github/github_faker.go
  monitorables/github/github_test.go
  monitorables/register_test.go
  pkg/gogithub/mocks/PullRequestService.go
  pkg/gogithub/pullrequest.go
  ui/src/classes/monitororTile.ts
  ui/src/components/SubTile.vue
  ui/src/components/Tile.vue
  ui/src/components/TileIcon.vue
  ui/src/enums/tileType.ts
  ui/src/interfaces/tileBuild.ts
  ui/src/interfaces/tileMergeRequest.ts
Labels: core, refactor, semver:minor, ui

#325 Add notes about JSON-escaping regex to documentation
  docs/documentation/index.html
Labels: documentation

#327 Break long words in labels
  ui/src/components/SubTile.vue
  ui/src/components/Tile.vue
Labels: enhancement, ui

#326 Make UI working even when served with route prefix
  ui/src/store.ts
  ui/vue.config.js
Labels: bug, ui

#334 Lowercase config name
  api/config/usecase/getconfig.go
  api/config/usecase/getconfig_test.go
Labels: enhancement

#333 Add MO_ADDRESS in documentation
  .env.example
  cli/printer/startup.go
  config/config.go
  docs/documentation/index.html
Labels: documentation

#332 Use PORT instead of PING in landing example
  docs/index.html
Labels: documentation

#339 Fix Go dependencies versions (and // indirect things)
  go.mod
  go.sum
Labels: core

#335 Welcome page
  .editorconfig
  .env.example
  cli/printer/startup.go
  cli/printer/startup_test.go
  docs/assets/styles/main.css
  faker-configs/welcome-config.json
  ui/public/fonts/open-sans-light.woff2
  ui/public/index.html
  ui/src/App.vue
  ui/src/components/Errors.vue
  ui/src/components/Welcome.vue
  ui/src/enums/route.ts
  ui/src/helpers/formatConfigExtract.ts
  ui/src/interfaces/configMetadata.ts
  ui/src/store.ts
Labels: feature, semver:minor, ui
