Repository monitoror/monitoror, pull requests merged in 2020-04, with the labels that each got.

#290 Improve start log readability
  cli/cli.go
  cli/cli_test.go
  cli/mocks/CLI.go
  cmd/monitoror/monitoror.go
  monitorables/azuredevops/azuredevops.go
  monitorables/monitorable.go
  monitorables/monitorable_test.go
  monitorables/pingdom/pingdom.go
  scripts/mock/mock.sh
  service/server.go
  service/server_test.go
  service/store/store.go
  service/ui.go
  service/ui_test.go
Labels: core, enhancement

#303 Add proxy script
  Makefile
  scripts/install-tools.sh
  scripts/proxy.sh
Labels: build/ci/cd

#304 Add .env.example with all env and default value
  .env.example
  .gitignore
  cmd/monitoror/monitoror.go
Labels: documentation

#311 fix(core/config): fix generatedTiles insertion inside tiles array
  api/config/usecase/hydrate.go
  api/config/usecase/hydrate_test.go
Labels: bug, core
